### ISSUE TITLE
An user should be able to update and delete their profile

### ISSUE THREAD

**Issue by NicoCPH** [deleplads/deleplads#49]
An user should be able to update their profile under their account.
Firstname and lastname is mandatory and shouldn't be deleted, so there need to be a cap on atleast 2 words on both.
Birth date is not mandatory
Phonenumber is not mandatory
Address, postal code and city should be defined together. So none of them can stand alone or with 2 defined

The user shoudl be prompted when the profile is updated with a toaster.

Shearch for toaster in the project, it is used somewhere else too.

An user should be able to delete their profile under their account which should delete the user aswell.

**Comment by bentreadwell** [comment]
Ideally, the user should have 30 days to log back into their account to reactivate it, after having deleted it. ✌️

**Comment by bentreadwell** [comment]
We're still missing image upload, which @cris391 is working on. 😉

**Comment by bentreadwell** [comment]
1. Have we implemented a 90-day grace period?
2. Are we saving the record of the user existing, after the 90-day grace period?
